// Export utilities for session data
// Supports PDF reports and audio file export

import jsPDF from 'jspdf';
import type { Session, Marker, Note, Adjournment } from '@/types/session';

interface ExportData {
  session: Session;
  markers: Marker[];
  notes: Note[];
  adjournments: Adjournment[];
  audioBlob?: Blob;
}

const formatTimestamp = (ms: number) => {
  const mins = Math.floor(ms / 60000);
  const secs = Math.floor((ms % 60000) / 1000);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
};

const formatDate = (date: Date | string) => {
  const d = typeof date === 'string' ? new Date(date) : date;
  return d.toLocaleDateString('en-NG', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
};

export async function exportToPDF(data: ExportData): Promise<void> {
  const { session, markers, notes, adjournments } = data;
  const pdf = new jsPDF();
  
  let yPos = 20;
  const pageHeight = pdf.internal.pageSize.height;
  const margin = 20;
  const lineHeight = 7;
  
  const checkNewPage = (requiredSpace: number = 20) => {
    if (yPos + requiredSpace > pageHeight - margin) {
      pdf.addPage();
      yPos = 20;
    }
  };

  // Header
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Court Session Report', margin, yPos);
  yPos += 12;

  // Generated by
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(128, 128, 128);
  pdf.text(`Generated by MyBarrister on ${formatDate(new Date())}`, margin, yPos);
  pdf.setTextColor(0, 0, 0);
  yPos += 15;

  // Session details
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Session Details', margin, yPos);
  yPos += lineHeight + 2;

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  
  if (session.caseTitle) {
    pdf.text(`Case: ${session.caseTitle}`, margin, yPos);
    yPos += lineHeight;
  }
  if (session.caseNumber) {
    pdf.text(`Case Number: ${session.caseNumber}`, margin, yPos);
    yPos += lineHeight;
  }
  if (session.courtName) {
    pdf.text(`Court: ${session.courtName}`, margin, yPos);
    yPos += lineHeight;
  }
  
  pdf.text(`Date: ${formatDate(session.createdAt)}`, margin, yPos);
  yPos += lineHeight;
  pdf.text(`Duration: ${formatTimestamp(session.totalDurationMs)}`, margin, yPos);
  yPos += lineHeight;
  pdf.text(`Recording Mode: ${session.recordingPosture === 'personal_notes' ? 'Personal Notes' : 'Open Recording'}`, margin, yPos);
  yPos += lineHeight;
  pdf.text(`Status: ${session.status.charAt(0).toUpperCase() + session.status.slice(1)}`, margin, yPos);
  yPos += lineHeight;
  pdf.text(`Review: ${session.reviewComplete ? 'Complete' : 'Pending'}`, margin, yPos);
  yPos += 15;

  // Markers section
  if (markers.length > 0) {
    checkNewPage(30);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Markers (${markers.length})`, margin, yPos);
    yPos += lineHeight + 2;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    
    markers.sort((a, b) => a.timestampMs - b.timestampMs).forEach((marker) => {
      checkNewPage();
      pdf.text(`[${formatTimestamp(marker.timestampMs)}] ${marker.label}`, margin, yPos);
      yPos += lineHeight;
    });
    yPos += 8;
  }

  // Notes section
  if (notes.length > 0) {
    checkNewPage(30);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Notes (${notes.length})`, margin, yPos);
    yPos += lineHeight + 2;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    
    notes.sort((a, b) => a.timestampMs - b.timestampMs).forEach((note) => {
      checkNewPage(20);
      const timestamp = `[${formatTimestamp(note.timestampMs)}]`;
      pdf.text(timestamp, margin, yPos);
      
      // Wrap note content
      const maxWidth = pdf.internal.pageSize.width - margin * 2;
      const splitText = pdf.splitTextToSize(note.content, maxWidth - 30);
      yPos += lineHeight;
      splitText.forEach((line: string) => {
        checkNewPage();
        pdf.text(line, margin + 10, yPos);
        yPos += lineHeight;
      });
      yPos += 3;
    });
    yPos += 5;
  }

  // Adjournments section
  if (adjournments.length > 0) {
    checkNewPage(30);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Adjournments (${adjournments.length})`, margin, yPos);
    yPos += lineHeight + 2;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    
    adjournments.sort((a, b) => a.timestampMs - b.timestampMs).forEach((adj) => {
      checkNewPage(25);
      pdf.text(`[${formatTimestamp(adj.timestampMs)}]`, margin, yPos);
      yPos += lineHeight;
      
      if (adj.nextDate) {
        pdf.text(`  Next Date: ${new Date(adj.nextDate).toLocaleDateString('en-NG')}`, margin, yPos);
        yPos += lineHeight;
      }
      if (adj.reason) {
        const maxWidth = pdf.internal.pageSize.width - margin * 2;
        const splitReason = pdf.splitTextToSize(`  Reason: ${adj.reason}`, maxWidth);
        splitReason.forEach((line: string) => {
          checkNewPage();
          pdf.text(line, margin, yPos);
          yPos += lineHeight;
        });
      }
      
      const confidenceText = adj.confidence === 'high' ? 'Confirmed' : 
                             adj.confidence === 'medium' ? 'Uncertain' : 
                             adj.confidence === 'unconfirmed' ? 'Unconfirmed' : 'Low Confidence';
      pdf.text(`  Confidence: ${confidenceText}`, margin, yPos);
      yPos += lineHeight + 5;
    });
  }

  // Footer
  checkNewPage(20);
  yPos = pageHeight - 15;
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text('This report is for personal legal use. Generated by MyBarrister.', margin, yPos);

  // Save PDF
  const fileName = session.caseTitle 
    ? `${session.caseTitle.replace(/[^a-zA-Z0-9]/g, '_')}_report.pdf`
    : `session_${session.id.slice(0, 8)}_report.pdf`;
  
  pdf.save(fileName);
}

export async function exportAudio(audioBlob: Blob, session: Session): Promise<void> {
  const url = URL.createObjectURL(audioBlob);
  const a = document.createElement('a');
  a.href = url;
  
  const fileName = session.caseTitle 
    ? `${session.caseTitle.replace(/[^a-zA-Z0-9]/g, '_')}_audio.webm`
    : `session_${session.id.slice(0, 8)}_audio.webm`;
  
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function exportNotes(data: ExportData): Promise<void> {
  const { session, markers, notes, adjournments } = data;
  
  let content = `# Court Session Notes\n\n`;
  content += `**Generated by MyBarrister on ${formatDate(new Date())}**\n\n`;
  content += `---\n\n`;
  
  content += `## Session Details\n\n`;
  if (session.caseTitle) content += `- **Case:** ${session.caseTitle}\n`;
  if (session.caseNumber) content += `- **Case Number:** ${session.caseNumber}\n`;
  if (session.courtName) content += `- **Court:** ${session.courtName}\n`;
  content += `- **Date:** ${formatDate(session.createdAt)}\n`;
  content += `- **Duration:** ${formatTimestamp(session.totalDurationMs)}\n`;
  content += `- **Status:** ${session.status}\n`;
  content += `- **Review:** ${session.reviewComplete ? 'Complete' : 'Pending'}\n\n`;

  if (markers.length > 0) {
    content += `## Markers\n\n`;
    markers.sort((a, b) => a.timestampMs - b.timestampMs).forEach((m) => {
      content += `- [${formatTimestamp(m.timestampMs)}] ${m.label}\n`;
    });
    content += `\n`;
  }

  if (notes.length > 0) {
    content += `## Notes\n\n`;
    notes.sort((a, b) => a.timestampMs - b.timestampMs).forEach((n) => {
      content += `### [${formatTimestamp(n.timestampMs)}]\n${n.content}\n\n`;
    });
  }

  if (adjournments.length > 0) {
    content += `## Adjournments\n\n`;
    adjournments.sort((a, b) => a.timestampMs - b.timestampMs).forEach((adj) => {
      content += `### [${formatTimestamp(adj.timestampMs)}]\n`;
      if (adj.nextDate) content += `- **Next Date:** ${new Date(adj.nextDate).toLocaleDateString('en-NG')}\n`;
      if (adj.reason) content += `- **Reason:** ${adj.reason}\n`;
      content += `- **Confidence:** ${adj.confidence}\n\n`;
    });
  }

  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  
  const fileName = session.caseTitle 
    ? `${session.caseTitle.replace(/[^a-zA-Z0-9]/g, '_')}_notes.md`
    : `session_${session.id.slice(0, 8)}_notes.md`;
  
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
